#!/bin/bash

OPENRAVE_DIR=$MUJIN_INSTALL_DIR/lib/python2.7/site-packages/openravepy/_openravepy_0_9
CURR_IKFAST_DIR=$MUJIN_JHBUILD_CHECKOUT_DIR/openrave/python

cp $CURR_IKFAST_DIR/*.py $OPENRAVE_DIR

cp $CURR_IKFAST_DIR/databases/*.py $OPENRAVE_DIR/databases

clear && clear

openrave.py --database inversekinematics --robot=../src/collada_robots/exactdynamics-manusarmleft.zae --numiktests=1000

#openrave.py --database inversekinematics --robot=../src/robots/schunk-lwa3-dual.robot.xml --numiktests=1000
