#!/bin/bash

OPENRAVE_DIR=$MUJIN_INSTALL_DIR/lib/python2.7/site-packages/openravepy/_openravepy_0_9
CURR_IKFAST_DIR=$MUJIN_JHBUILD_CHECKOUT_DIR/openrave/python

cp $CURR_IKFAST_DIR/*.py $OPENRAVE_DIR

cp $CURR_IKFAST_DIR/databases/*.py $OPENRAVE_DIR/databases

clear && clear

DIRNAME=$1
ZAEFILES=`sudo ls $DIRNAME/*.zae $DIRNAME/*.xml $DIRNAME/*.dae`

rm -f *.log /var/tmp/ikfast-*.log *.out

for f in $ZAEFILES
do
    openrave.py --database inversekinematics --robot=$f --numiktests=1000
    sleep 3
done
