#!/bin/bash

#nohup ./test_all ../src/collada_robots/ &

OPENRAVE_DIR=$MUJIN_INSTALL_DIR/lib/python2.7/site-packages/openravepy/_openravepy_0_9
CURR_IKFAST_DIR=$MUJIN_JHBUILD_CHECKOUT_DIR/openrave/python

cp $CURR_IKFAST_DIR/*.py $OPENRAVE_DIR

cp $CURR_IKFAST_DIR/databases/*.py $OPENRAVE_DIR/databases

clear && clear

./test_all robotfiles

openrave.py --database inversekinematics \
            --robot=robotfiles/neuronics-katana.zae \
            --iktype=translationdirection5d \
            --manipname=arm \
            --numiktests=1000
